### ISSUE TITLE
The module is not working and causes bootloop with Android 10

### ISSUE THREAD

**Issue by MarcAnt01** [Magisk-Modules-Repo/op3frontcamfix#2]
I am still waiting for some bootlogs, but most users like to complain without giving me what should be needed to fix since I don't have a OnePlus 3 any longer.

**Comment by Athi07** [comment]
How to send logs. I can send

**Comment by abhiboby** [comment]
> How to send logs. I can send

Hi raa I'm Abhi lol

**Comment by MarcAnt01** [comment]
https://forum.xda-developers.com/showthread.php?t=1726238

**Comment by Athi07** [comment]
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
error: exec '/system/bin/sh' failed: No such file or directory

**Comment by MarcAnt01** [comment]
> * daemon not running. starting it now on port 5037 *
> * daemon started successfully *
>   error: exec '/system/bin/sh' failed: No such file or directory

I need full logs, don’t shorten them for me

**Comment by Athi07** [comment]
> > * daemon not running. starting it now on port 5037 *
> > * daemon started successfully *
> >   error: exec '/system/bin/sh' failed: No such file or directory
> 
> I need full logs, don’t shorten them for me

Only this is the log I got.

**Comment by MarcAnt01** [comment]
Then, I have no idea about how to fix that, will leave this ticket open in case someone wants to fix via PR

**Comment by Ahsanulhoq** [comment]
[jahinnn.txt](https://github.com/Magisk-Modules-Repo/op3frontcamfix/files/3917986/jahinnn.txt)

**Comment by Athi07** [comment]
@MarcAnt01 . Is it good enough?

**Comment by MarcAnt01** [comment]
@Athi07 wdym?

**Comment by Athi07** [comment]
> @Athi07 wdym?

Can u do the fix?

**Comment by MarcAnt01** [comment]
Fixed
